### ISSUE TITLE
Unexpected behavior in Gitpod environment

### ISSUE THREAD

**Issue by rvanasa** [B3Pay/ic-reactor#2]
This is a follow-up from https://github.com/rvanasa/vite-react-motoko/pull/12.

When using the "Open in Gitpod" link on the [Vite + React + Motoko](https://github.com/rvanasa/vite-react-motoko#readme) readme, the project currently breaks with an error message along the lines of "IC0536: Canister bkyz2-fmaaa-aaaaa-qaaaq-cai has no query method 'get'". 

This probably has something to do with `@ic-reactor/react` trying to use the ICP mainnet instead of the local Gitpod environment, which is handled in `@dfinity/agent` by default. Here is the [relevant source code](https://github.com/dfinity/agent-js/blob/a51bd5b837fd5f98daca5a45dfc4a060a315e62e/packages/agent/src/agent/http/index.ts#L245) in case this is helpful for resolving the issue.

**Comment by b3hr4d** [comment]
Thank you for bringing this. I've run the project on gitpod and it seems to be working as expected on my end. Could you please provide the instructions you followed so I can try to reproduce the issue?

**Comment by b3hr4d** [comment]
Ok, I have managed to to reproduce it,you are right its about the agent connection.
I'll fix it as soon as I can ✌🏻

**Comment by rvanasa** [comment]
Thank you; cheers!

**Comment by b3hr4d** [comment]
I have published a beta version `@ic-reactor/react@1.5.5-beta.0` and tested it on my end, can you please confirm it is working as expected?

**Comment by rvanasa** [comment]
Works as expected! thank you for the quick rollout of this solution.
